apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-battle-ui
  labels:
    app: github-battle-ui
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
      app: github-battle-ui
  replicas: 1
  template:
    metadata:
      labels:
        tier: frontend
        app: github-battle-ui
    spec:
      containers:
      - name: github-battle-ui
        image: flaviomattos86/github-battle-hooks:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: github-battle-ui-service
spec:
  selector:
    tier: frontend
    app: github-battle-ui
  type: NodePort
  ports:
  - protocol: TCP
    port: 80